#!/bin/bash
PORT=$1
TENANT=$2

# Set Port Number
if [ "$PORT" = "" ]; then
	PORT=`cat port.txt` || TENANT="9999"
	echo "Port set to: $PORT"
fi

# Set Tenant Number
if [ "$TENANT" = "" ]; then
	TENANT=`cat tenant.txt` || TENANT=9999
	echo "Tenant set to: $TENANT"
fi

TENANTNAME="tenant$TENANT" 
echo "Tenant Name: $TENANTNAME"

#echo '### 1) Pulling most recent commit from master'
# git checkout master
# git pull

echo '### 2) Entering Virtual Environment'
source env/bin/activate

# echo '### 3) Kill existing gunicorn instances'
# pkill -U henkhaus $TENANTNAME

python app.py